codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: null
        base: pr
      prisma-electron:
        paths:
          - packages/prisma-electron/**/*
      prisma-map:
        paths:
          - packages/prisma-map/**/*
      prisma-ui:
        paths:
          - packages/prisma-ui/**/*
ignore:
  - "packages/prisma-electron/test/**/*"
  - "**/*.spec.*"
  - "**/*.stories.*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
