version: 0.2

env:
  parameter-store:
    CODECOV_TOKEN: CODECOV_ACCOUNT_TOKEN
phases:
  pre_build:
    commands:
      - TZ='America/New_York'; export TZ
      - env
      - node --version
      - yarn -version
      - yarn install --silent --non-interactive
  build:
    commands:
      - echo Build started on `date`
      - yarn build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Tests started on `date`
      - export VCS_COMMIT_ID="$(git rev-parse HEAD)"
      - yarn test:coverage:codecov -y ./codecov.yml -B ${CODEBUILD_BUILD_ID} -X detect -c $VCS_COMMIT_ID
      - echo Tests completed on `date`
artifacts:
  files:
    - coverage/**/*
  base-directory: ${CODEBUILD_SRC_DIR}/
  name: prisma-ui
