version: 0.2

env:
  parameter-store:
    CODECOV_TOKEN: CODECOV_ACCOUNT_TOKEN
phases:
  pre_build:
    commands:
      - TZ='America/New_York'; export TZ
      - export DOCUMENTATION_FOLDER=$([ $CODEBUILD_WEBHOOK_HEAD_REF = 'refs/heads/master' ] && echo "latest" || echo "nightly")
      - env
      - node --version
      - yarn -version
      - cd ${CODEBUILD_SRC_DIR}/
      - yarn install --silent --non-interactive
  build:
    commands:
      - echo Build started on `date`
      - cd ${CODEBUILD_SRC_DIR}/
      - yarn build
      - yarn build:storybook
      - yarn build:docs
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Tests started on `date`
      - cd ${CODEBUILD_SRC_DIR}/
      - export VCS_COMMIT_ID="$(git rev-parse HEAD)"
      - yarn test:coverage:codecov -y ./codecov.yml -B ${CODEBUILD_BUILD_ID} -X detect -c $VCS_COMMIT_ID
      - echo Tests completed on `date`
      - echo Deploying Storybooks
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-electron/dist/storybook-static
      - aws s3 sync . s3://prisma-storybook/prisma-electron/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-map/storybook-static
      - aws s3 sync . s3://prisma-storybook/prisma-map/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-ui/storybook-static
      - aws s3 sync . s3://prisma-storybook/prisma-ui/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - aws cloudfront create-invalidation --distribution-id=ERTGKWV7VS8OB --paths "/prisma-electron/${DOCUMENTATION_FOLDER}/*" "/prisma-ui/${DOCUMENTATION_FOLDER}/*" "/prisma-map/${DOCUMENTATION_FOLDER}/*"
      - echo Deploying Documentation Site
      - cd ${CODEBUILD_SRC_DIR}/dist/documentation_site
      - aws s3 sync . s3://prisma-documentation/prisma-ui/${DOCUMENTATION_FOLDER}/ --delete --quiet
      - aws cloudfront create-invalidation --distribution-id=E3HJFQ1L5X1NOH --paths "/prisma-ui/${DOCUMENTATION_FOLDER}/*"
artifacts:
  files:
    - coverage/**/*
  base-directory: ${CODEBUILD_SRC_DIR}/
  name: prisma-ui
