version: 0.2

phases:
  pre_build:
    commands:
      - export VERSION=$(git tag --points-at HEAD | tr -d v)
      - TZ='America/New_York'; export TZ
      - env
      - node --version
      - yarn -version
      - wine --version
      - mono --version
      - yarn install --silent --non-interactive
  build:
    commands:
      - echo Build started on `date`
      - yarn build:map && yarn build:ui
      - cp /opt/7zip/* node_modules/electron-winstaller/vendor/
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-electron/node_modules/
      - rm -rf ./@prisma
      - mkdir -p ./@prisma/map
      - cp -r ${CODEBUILD_SRC_DIR}/packages/prisma-map/dist/* ./@prisma/map/
      - mkdir -p ./@prisma/ui
      - cp -r ${CODEBUILD_SRC_DIR}/packages/prisma-ui/dist/* ./@prisma/ui/
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-electron
      - yarn dist:windows
      - yarn package:macOS
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ${CODEBUILD_SRC_DIR}/packages/prisma-electron/
      - mv dist/installer/windows/PRISMASetup.exe dist/installer/windows/PRISMASetup-${VERSION}.exe

artifacts:
  files:
    - dist/installer/**/*
    - dist/package/**/*.tar.gz
    - dist/package/**/*.zip
  base-directory: ${CODEBUILD_SRC_DIR}/packages/prisma-electron
  name: ${VERSION}
