/*
 * COPYRIGHT © 2018 OROLIA GROUP AND/OR ITS AFFILIATES. ALL RIGHTS ARE STRICTLY RESERVED.
 * THIS SOURCE CODE CONTAINS PROPRIETARY AND CONFIDENTIAL INFORMATION AND DATA AND IS THE
 * SOLE PROPERTY OF OROLIA GROUP AND/OR ITS AFFILIATES.
 * THIS SOURCE CODE MUST NOT BE USED, DISSEMINATED, OR DISTRIBUTED EXCEPT FOR THE AGREED PURPOSE.
 * UNAUTHORIZED USE, REPRODUCTION, OR ISSUE TO ANY THIRD PARTY IS NOT PERMITTED WITHOUT THE
 * PRIOR WRITTEN CONSENT OF THE OROLIA GROUP.
 * THIS SOURCE CODE IS TO BE RETURNED TO THE OROLIA GROUP WHEN THE AGREED PURPOSE IS FULFILLED.
 * -------------------------------------
 */

// Draw Mode
export const START_DRAW_MODE = 'Map/Mode/START_DRAW';
export const STOP_DRAW_MODE = 'Map/Mode/STOP_DRAW';

// Tools
export const CHANGE_DRAW_TOOL = 'Map/Mode/Draw/CHANGE_TOOL';

// Features to/from draw tool
export const ADD_DRAW_FEATURE = 'Map/Mode/Draw/ADD_FEATURE';
export const DRAW_FEATURE_CREATED = 'Map/Mode/Draw/FEATURE_CREATED';
export const DRAW_FEATURE_UPDATED = 'Map/Mode/Draw/FEATURE_UPDATED';
export const DRAW_FEATURE_REMOVED = 'Map/Mode/Draw/FEATURE_REMOVED';
