import i18n from '../i18n';

const __ = i18n.namespace('country');

export default {
  AD: __('Andorra'),
  AE: __('United Arab Emirates'),
  AF: __('Afghanistan'),
  AG: __('Antigua and Barbuda'),
  AI: __('Anguilla'),
  AL: __('Albania'),
  AO: __('Angola'),
  AQ: __('Kerguelen Islands'),
  AR: __('Argentina'),
  AS: __('American Samoa'),
  AT: __('Austria'),
  AU: __('Australia'),
  AW: __('Aruba'),
  AZ: __('Azerbaijani Republic'),
  BA: __('Bosnia and Herzegovina'),
  BB: __('Barbados'),
  BD: __('Bangladesh'),
  BE: __('Belgium'),
  BF: __('Burkina Faso'),
  BG: __('Bulgaria'),
  BH: __('Bahrain'),
  BI: __('Burundi'),
  BJ: __('Benin'),
  BM: __('Bermuda'),
  BN: __('Brunei'),
  BO: __('Bolivia'),
  BR: __('Brazil'),
  BS: __('Bahamas'),
  BT: __('Bhutan'),
  BW: __('Botswana'),
  BY: __('Belarus'),
  BZ: __('Belize'),
  CA: __('Canada'),
  CC: __('Cocos (Keeling) Islands'),
  CD: __('Democratic Republic of the Congo'),
  CF: __('Central African Republic'),
  CG: __('Congo'),
  CH: __('Switzerland'),
  CI: __("Cote d'Ivoire"),
  CK: __('Cook Islands'),
  CL: __('Chile'),
  CM: __('Cameroon'),
  CN: __('China'),
  CO: __('Colombia'),
  CR: __('Costa Rica'),
  CU: __('Cuba'),
  CV: __('Cape Verde'),
  CW: __('Netherlands Antilles'),
  CX: __('Christmas Island'),
  CY: __('Northern Cyprus'),
  CZ: __('Czech Republic'),
  DE: __('Germany'),
  DJ: __('Djibouti'),
  DK: __('Denmark'),
  DM: __('Dominica'),
  DO: __('Dominican Republic'),
  DZ: __('Algeria'),
  EC: __('Ecuador'),
  EE: __('Estonia'),
  EG: __('Egypt'),
  ER: __('Eritrea'),
  ES: __('Spain'),
  ET: __('Ethiopia'),
  FI: __('Finland'),
  FJ: __('Fiji'),
  FK: __('Falkland Islands'),
  FM: __('Federated States of Micronesia'),
  FO: __('Faroe Islands'),
  FR: __('France'),
  GA: __('Gabon'),
  GB: __('United Kingdom'),
  GD: __('Grenada'),
  GE: __('Georgia'),
  GF: __('Guiana'),
  GH: __('Ghana'),
  GI: __('Gibraltar'),
  GL: __('Greenland'),
  GM: __('Gambia'),
  GN: __('Guinea'),
  GP: __('France'),
  GQ: __('Equatorial Guinea'),
  GR: __('Greece'),
  GT: __('Guatemala'),
  GW: __('Guinea-Bissau'),
  GY: __('Guyana'),
  HK: __('Hong Kong'),
  HN: __('Honduras'),
  HR: __('Croatia'),
  HT: __('Haiti'),
  HU: __('Hungary'),
  ID: __('Indonesia'),
  IE: __('Ireland'),
  IL: __('Israel'),
  IN: __('India'),
  IO: __('Ascension Island'),
  IQ: __('Iraq'),
  IR: __('Iran'),
  IS: __('Iceland'),
  IT: __('Italy'),
  JM: __('Jamaica'),
  JO: __('Jordan'),
  JP: __('Japan'),
  KE: __('Kenya'),
  KH: __('Cambodia'),
  KI: __('Kiribati'),
  KM: __('Comoros'),
  KN: __('Saint Kitts and Nevis'),
  KP: __('North Korea'),
  KR: __('South Korea'),
  KW: __('Kuwait'),
  KY: __('Cayman Islands'),
  KZ: __('Kazakhstan'),
  LA: __('Laos'),
  LB: __('Lebanon'),
  LC: __('Saint Lucia'),
  LI: __('Liechtenstein'),
  LK: __('Sri Lanka'),
  LR: __('Liberia'),
  LS: __('Lesotho'),
  LT: __('Lithuania'),
  LU: __('Luxembourg'),
  LV: __('Latvia'),
  LY: __('Libya'),
  MA: __('Morocco'),
  MC: __('Monaco'),
  MD: __('Moldova'),
  ME: __('Montenegro'),
  MG: __('Madagascar'),
  MH: __('Marshall Islands'),
  MK: __('Macedonia'),
  ML: __('Mali'),
  MM: __('Myanmar'),
  MN: __('Mongolia'),
  MP: __('Northern Mariana Islands'),
  MQ: __('Martinique'),
  MR: __('Mauritania'),
  MS: __('Montserrat'),
  MT: __('Malta'),
  MU: __('Mauritius'),
  MV: __('Maldives'),
  MW: __('Malawi'),
  MX: __('Mexico'),
  MY: __('Malaysia'),
  MZ: __('Mozambique'),
  NA: __('Namibia'),
  NC: __('New Caledonia'),
  NE: __('Niger'),
  NG: __('Nigeria'),
  NI: __('Nicaragua'),
  NL: __('Netherlands'),
  NO: __('Norway'),
  NP: __('Nepal'),
  NR: __('Nauru'),
  NU: __('Niue'),
  NZ: __('New Zealand'),
  OM: __('Oman'),
  PA: __('Panama'),
  PE: __('Peru'),
  PG: __('Papua New Guinea'),
  PH: __('Philippines'),
  PK: __('Pakistan'),
  PL: __('Poland'),
  PM: __('Saint Pierre and Miquelon'),
  PN: __('Pitcairn Island'),
  PR: __('Puerto Rico'),
  PS: __('Palestine'),
  PT: __('Portugal'),
  PW: __('Palau'),
  PY: __('Paraguay'),
  QA: __('Qatar'),
  RE: __('Reunion'),
  RO: __('Romania'),
  RS: __('Serbia'),
  RU: __('Russian Federation'),
  RW: __('Rwanda'),
  SA: __('Saudi Arabia'),
  SB: __('Solomon Islands'),
  SC: __('Seychelles'),
  SD: __('Sudan'),
  SE: __('Sweden'),
  SG: __('Singapore'),
  SH: __('Saint Helena'),
  SI: __('Slovenia'),
  SK: __('Slovak Republic'),
  SL: __('Sierra Leone'),
  SM: __('San Marino'),
  SN: __('Senegal'),
  SO: __('Somalia'),
  SR: __('Suriname'),
  ST: __('Sao Tome and Principe'),
  SV: __('El Salvador'),
  SY: __('Syria'),
  SZ: __('Swaziland'),
  TC: __('Turks and Caicos Islands'),
  TD: __('Chad'),
  TF: __('French Polynesia'),
  TG: __('Togo'),
  TH: __('Thailand'),
  TM: __('Turkmenistan'),
  TN: __('Tunisia'),
  TO: __('Tonga'),
  TR: __('Turkey'),
  TT: __('Trinidad and Tobago'),
  TV: __('Tuvalu'),
  TW: __('Taiwan'),
  TZ: __('Tanzania'),
  UA: __('Ukraine'),
  UG: __('Uganda'),
  US: __('United States of America'),
  UY: __('Uruguay'),
  UZ: __('Uzbekistan'),
  VA: __('Vatican City State'),
  VC: __('Saint Vincent and the Grenadines'),
  VE: __('Venezuela'),
  VG: __('British Virgin Islands'),
  VI: __('United States Virgin Islands'),
  VN: __('Vietnam'),
  VU: __('Vanuatu'),
  WF: __('Wallis and Futuna Islands'),
  WS: __('Samoa'),
  XX: __('Saint Paul and Amsterdam Islands'),
  YE: __('Yemen'),
  ZA: __('South Africa'),
  ZM: __('Zambia'),
  ZW: __('Zimbabwe'),
  ZZ: __('Macao'),
};
